# config/application.yml
defaults: &defaults
  web_frontend:
    price_ticker:
      enabled: <%= ENV['WEB_FRONTEND_PRICE_TICKER_ENABLED'] %>
      refresh: <%= ENV['WEB_FRONTEND_PRICE_TICKER_REFRESH'] %>

  coinbase:
    api:
      base_url: <%= ENV['COINBASE_API_BASE_URL'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults